name: flutter_weather
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  json_annotation: ^4.8.1
  bloc: 8.1.2
  flutter_bloc: 8.1.3
  equatable: 2.0.5 
  google_fonts: ^6.1.0
  intl: 0.18.1
  cached_network_image: 3.3.0
  weather_animation: 1.0.1

  cupertino_icons: ^1.0.2

  # Code gen
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1

  # Dio
  dio: 5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mocktail: ^1.0.0
  test: ^1.16.4

  
  flutter_lints: ^3.0.1


flutter:

  
  uses-material-design: true
  generate: false

  assets:
    - assets/images/
